server:
  port: 8080

spring:
  application:
    name: repair-server

  datasource:
    # ???? Docker ??? MySQL
    url: jdbc:mysql://localhost:3306/community_repair?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # ??? Java ????????
    hibernate:
      ddl-auto: update
    # ?????? SQL ????????
    show-sql: true